export const links = {
  home: 'https://www.validium.network',
  explorer: 'https://devnet.explorer.validium.network',
  discord: '',
  github: 'https://github.com/Validium-Chain',
  docs: 'https://validium.gitbook.io/docs',
  warpDocs: '',
  gasDocs: '',
  chains: '',
  twitter: 'https://x.com/validiumnetwork?s=21&t=9cg0BJs-HsjOBKIeKeVH8A',
  blog: 'https://medium.com/@validium',
  whitepaper: 'https://docsend.com/view/5c85m6dfy3v4rren',
  faucet: 'https://devnet.faucet.validium.network/',
  tos: '',
  privacyPolicy: '',
  linkedin: 'https://www.linkedin.com/company/validiumnetwork/',
  bounty:
    'https://github.com/search?q=org:hyperlane-xyz+label:bounty+is:open+is:issue&type=issues&s=&o=desc',
    bridgel1tol2:'https://devnet.bridge.validium.network/bridge',
};
